
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point enable enable -type PI PI
add mapped point v_in[15] v_in[15] -type PI PI
add mapped point v_in[14] v_in[14] -type PI PI
add mapped point v_in[13] v_in[13] -type PI PI
add mapped point v_in[12] v_in[12] -type PI PI
add mapped point v_in[11] v_in[11] -type PI PI
add mapped point v_in[10] v_in[10] -type PI PI
add mapped point v_in[9] v_in[9] -type PI PI
add mapped point v_in[8] v_in[8] -type PI PI
add mapped point v_in[7] v_in[7] -type PI PI
add mapped point v_in[6] v_in[6] -type PI PI
add mapped point v_in[5] v_in[5] -type PI PI
add mapped point v_in[4] v_in[4] -type PI PI
add mapped point v_in[3] v_in[3] -type PI PI
add mapped point v_in[2] v_in[2] -type PI PI
add mapped point v_in[1] v_in[1] -type PI PI
add mapped point v_in[0] v_in[0] -type PI PI
add mapped point target[15] target[15] -type PI PI
add mapped point target[14] target[14] -type PI PI
add mapped point target[13] target[13] -type PI PI
add mapped point target[12] target[12] -type PI PI
add mapped point target[11] target[11] -type PI PI
add mapped point target[10] target[10] -type PI PI
add mapped point target[9] target[9] -type PI PI
add mapped point target[8] target[8] -type PI PI
add mapped point target[7] target[7] -type PI PI
add mapped point target[6] target[6] -type PI PI
add mapped point target[5] target[5] -type PI PI
add mapped point target[4] target[4] -type PI PI
add mapped point target[3] target[3] -type PI PI
add mapped point target[2] target[2] -type PI PI
add mapped point target[1] target[1] -type PI PI
add mapped point target[0] target[0] -type PI PI

//output ports
add mapped point v_amplified[15] v_amplified[15] -type PO PO
add mapped point v_amplified[14] v_amplified[14] -type PO PO
add mapped point v_amplified[13] v_amplified[13] -type PO PO
add mapped point v_amplified[12] v_amplified[12] -type PO PO
add mapped point v_amplified[11] v_amplified[11] -type PO PO
add mapped point v_amplified[10] v_amplified[10] -type PO PO
add mapped point v_amplified[9] v_amplified[9] -type PO PO
add mapped point v_amplified[8] v_amplified[8] -type PO PO
add mapped point v_amplified[7] v_amplified[7] -type PO PO
add mapped point v_amplified[6] v_amplified[6] -type PO PO
add mapped point v_amplified[5] v_amplified[5] -type PO PO
add mapped point v_amplified[4] v_amplified[4] -type PO PO
add mapped point v_amplified[3] v_amplified[3] -type PO PO
add mapped point v_amplified[2] v_amplified[2] -type PO PO
add mapped point v_amplified[1] v_amplified[1] -type PO PO
add mapped point v_amplified[0] v_amplified[0] -type PO PO
add mapped point v_filtered[15] v_filtered[15] -type PO PO
add mapped point v_filtered[14] v_filtered[14] -type PO PO
add mapped point v_filtered[13] v_filtered[13] -type PO PO
add mapped point v_filtered[12] v_filtered[12] -type PO PO
add mapped point v_filtered[11] v_filtered[11] -type PO PO
add mapped point v_filtered[10] v_filtered[10] -type PO PO
add mapped point v_filtered[9] v_filtered[9] -type PO PO
add mapped point v_filtered[8] v_filtered[8] -type PO PO
add mapped point v_filtered[7] v_filtered[7] -type PO PO
add mapped point v_filtered[6] v_filtered[6] -type PO PO
add mapped point v_filtered[5] v_filtered[5] -type PO PO
add mapped point v_filtered[4] v_filtered[4] -type PO PO
add mapped point v_filtered[3] v_filtered[3] -type PO PO
add mapped point v_filtered[2] v_filtered[2] -type PO PO
add mapped point v_filtered[1] v_filtered[1] -type PO PO
add mapped point v_filtered[0] v_filtered[0] -type PO PO
add mapped point v_mac_out[15] v_mac_out[15] -type PO PO
add mapped point v_mac_out[14] v_mac_out[14] -type PO PO
add mapped point v_mac_out[13] v_mac_out[13] -type PO PO
add mapped point v_mac_out[12] v_mac_out[12] -type PO PO
add mapped point v_mac_out[11] v_mac_out[11] -type PO PO
add mapped point v_mac_out[10] v_mac_out[10] -type PO PO
add mapped point v_mac_out[9] v_mac_out[9] -type PO PO
add mapped point v_mac_out[8] v_mac_out[8] -type PO PO
add mapped point v_mac_out[7] v_mac_out[7] -type PO PO
add mapped point v_mac_out[6] v_mac_out[6] -type PO PO
add mapped point v_mac_out[5] v_mac_out[5] -type PO PO
add mapped point v_mac_out[4] v_mac_out[4] -type PO PO
add mapped point v_mac_out[3] v_mac_out[3] -type PO PO
add mapped point v_mac_out[2] v_mac_out[2] -type PO PO
add mapped point v_mac_out[1] v_mac_out[1] -type PO PO
add mapped point v_mac_out[0] v_mac_out[0] -type PO PO
add mapped point v_act_out[15] v_act_out[15] -type PO PO
add mapped point v_act_out[14] v_act_out[14] -type PO PO
add mapped point v_act_out[13] v_act_out[13] -type PO PO
add mapped point v_act_out[12] v_act_out[12] -type PO PO
add mapped point v_act_out[11] v_act_out[11] -type PO PO
add mapped point v_act_out[10] v_act_out[10] -type PO PO
add mapped point v_act_out[9] v_act_out[9] -type PO PO
add mapped point v_act_out[8] v_act_out[8] -type PO PO
add mapped point v_act_out[7] v_act_out[7] -type PO PO
add mapped point v_act_out[6] v_act_out[6] -type PO PO
add mapped point v_act_out[5] v_act_out[5] -type PO PO
add mapped point v_act_out[4] v_act_out[4] -type PO PO
add mapped point v_act_out[3] v_act_out[3] -type PO PO
add mapped point v_act_out[2] v_act_out[2] -type PO PO
add mapped point v_act_out[1] v_act_out[1] -type PO PO
add mapped point v_act_out[0] v_act_out[0] -type PO PO
add mapped point weight_out[15] weight_out[15] -type PO PO
add mapped point weight_out[14] weight_out[14] -type PO PO
add mapped point weight_out[13] weight_out[13] -type PO PO
add mapped point weight_out[12] weight_out[12] -type PO PO
add mapped point weight_out[11] weight_out[11] -type PO PO
add mapped point weight_out[10] weight_out[10] -type PO PO
add mapped point weight_out[9] weight_out[9] -type PO PO
add mapped point weight_out[8] weight_out[8] -type PO PO
add mapped point weight_out[7] weight_out[7] -type PO PO
add mapped point weight_out[6] weight_out[6] -type PO PO
add mapped point weight_out[5] weight_out[5] -type PO PO
add mapped point weight_out[4] weight_out[4] -type PO PO
add mapped point weight_out[3] weight_out[3] -type PO PO
add mapped point weight_out[2] weight_out[2] -type PO PO
add mapped point weight_out[1] weight_out[1] -type PO PO
add mapped point weight_out[0] weight_out[0] -type PO PO
add mapped point gradient_out[15] gradient_out[15] -type PO PO
add mapped point gradient_out[14] gradient_out[14] -type PO PO
add mapped point gradient_out[13] gradient_out[13] -type PO PO
add mapped point gradient_out[12] gradient_out[12] -type PO PO
add mapped point gradient_out[11] gradient_out[11] -type PO PO
add mapped point gradient_out[10] gradient_out[10] -type PO PO
add mapped point gradient_out[9] gradient_out[9] -type PO PO
add mapped point gradient_out[8] gradient_out[8] -type PO PO
add mapped point gradient_out[7] gradient_out[7] -type PO PO
add mapped point gradient_out[6] gradient_out[6] -type PO PO
add mapped point gradient_out[5] gradient_out[5] -type PO PO
add mapped point gradient_out[4] gradient_out[4] -type PO PO
add mapped point gradient_out[3] gradient_out[3] -type PO PO
add mapped point gradient_out[2] gradient_out[2] -type PO PO
add mapped point gradient_out[1] gradient_out[1] -type PO PO
add mapped point gradient_out[0] gradient_out[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point error_signal[0]/q error_signal_reg[0]/Q -type DFF DFF
add mapped point error_signal[1]/q error_signal_reg[1]/Q -type DFF DFF
add mapped point error_signal[2]/q error_signal_reg[2]/Q -type DFF DFF
add mapped point error_signal[3]/q error_signal_reg[3]/Q -type DFF DFF
add mapped point error_signal[4]/q error_signal_reg[4]/Q -type DFF DFF
add mapped point error_signal[5]/q error_signal_reg[5]/Q -type DFF DFF
add mapped point error_signal[6]/q error_signal_reg[6]/Q -type DFF DFF
add mapped point error_signal[7]/q error_signal_reg[7]/Q -type DFF DFF
add mapped point error_signal[8]/q error_signal_reg[8]/Q -type DFF DFF
add mapped point error_signal[9]/q error_signal_reg[9]/Q -type DFF DFF
add mapped point error_signal[10]/q error_signal_reg[10]/Q -type DFF DFF
add mapped point error_signal[11]/q error_signal_reg[11]/Q -type DFF DFF
add mapped point error_signal[12]/q error_signal_reg[12]/Q -type DFF DFF
add mapped point error_signal[13]/q error_signal_reg[13]/Q -type DFF DFF
add mapped point error_signal[14]/q error_signal_reg[14]/Q -type DFF DFF
add mapped point error_signal[15]/q error_signal_reg[15]/Q -type DFF DFF
add mapped point filt_mult[8]/q filt_mult_reg[8]/Q -type DFF DFF
add mapped point filt_mult[9]/q filt_mult_reg[9]/Q -type DFF DFF
add mapped point filt_mult[10]/q filt_mult_reg[10]/Q -type DFF DFF
add mapped point filt_mult[11]/q filt_mult_reg[11]/Q -type DFF DFF
add mapped point filt_mult[12]/q filt_mult_reg[12]/Q -type DFF DFF
add mapped point filt_mult[13]/q filt_mult_reg[13]/Q -type DFF DFF
add mapped point filt_mult[14]/q filt_mult_reg[14]/Q -type DFF DFF
add mapped point filt_mult[15]/q filt_mult_reg[15]/Q -type DFF DFF
add mapped point filt_mult[16]/q filt_mult_reg[16]/Q -type DFF DFF
add mapped point filt_mult[17]/q filt_mult_reg[17]/Q -type DFF DFF
add mapped point filt_mult[18]/q filt_mult_reg[18]/Q -type DFF DFF
add mapped point filt_mult[19]/q filt_mult_reg[19]/Q -type DFF DFF
add mapped point filt_mult[20]/q filt_mult_reg[20]/Q -type DFF DFF
add mapped point filt_mult[21]/q filt_mult_reg[21]/Q -type DFF DFF
add mapped point gm_mult[11]/q gm_mult_reg[11]/Q -type DFF DFF
add mapped point gm_mult[12]/q gm_mult_reg[12]/Q -type DFF DFF
add mapped point gm_mult[13]/q gm_mult_reg[13]/Q -type DFF DFF
add mapped point gm_mult[14]/q gm_mult_reg[14]/Q -type DFF DFF
add mapped point gm_mult[15]/q gm_mult_reg[15]/Q -type DFF DFF
add mapped point gm_mult[16]/q gm_mult_reg[16]/Q -type DFF DFF
add mapped point gm_mult[17]/q gm_mult_reg[17]/Q -type DFF DFF
add mapped point gm_mult[18]/q gm_mult_reg[18]/Q -type DFF DFF
add mapped point gm_mult[19]/q gm_mult_reg[19]/Q -type DFF DFF
add mapped point gm_mult[20]/q gm_mult_reg[20]/Q -type DFF DFF
add mapped point gm_mult[21]/q gm_mult_reg[21]/Q -type DFF DFF
add mapped point gm_mult[22]/q gm_mult_reg[22]/Q -type DFF DFF
add mapped point gm_mult[23]/q gm_mult_reg[23]/Q -type DFF DFF
add mapped point grad_mult[8]/q grad_mult_reg[8]/Q -type DFF DFF
add mapped point grad_mult[9]/q grad_mult_reg[9]/Q -type DFF DFF
add mapped point grad_mult[10]/q grad_mult_reg[10]/Q -type DFF DFF
add mapped point grad_mult[11]/q grad_mult_reg[11]/Q -type DFF DFF
add mapped point grad_mult[12]/q grad_mult_reg[12]/Q -type DFF DFF
add mapped point grad_mult[13]/q grad_mult_reg[13]/Q -type DFF DFF
add mapped point grad_mult[14]/q grad_mult_reg[14]/Q -type DFF DFF
add mapped point grad_mult[15]/q grad_mult_reg[15]/Q -type DFF DFF
add mapped point grad_mult[16]/q grad_mult_reg[16]/Q -type DFF DFF
add mapped point grad_mult[17]/q grad_mult_reg[17]/Q -type DFF DFF
add mapped point grad_mult[18]/q grad_mult_reg[18]/Q -type DFF DFF
add mapped point grad_mult[19]/q grad_mult_reg[19]/Q -type DFF DFF
add mapped point grad_mult[20]/q grad_mult_reg[20]/Q -type DFF DFF
add mapped point grad_mult[21]/q grad_mult_reg[21]/Q -type DFF DFF
add mapped point grad_mult[22]/q grad_mult_reg[22]/Q -type DFF DFF
add mapped point grad_mult[23]/q grad_mult_reg[23]/Q -type DFF DFF
add mapped point mac_acc[0]/q mac_acc_reg[0]/Q -type DFF DFF
add mapped point mac_acc[1]/q mac_acc_reg[1]/Q -type DFF DFF
add mapped point mac_acc[2]/q mac_acc_reg[2]/Q -type DFF DFF
add mapped point mac_acc[3]/q mac_acc_reg[3]/Q -type DFF DFF
add mapped point mac_acc[4]/q mac_acc_reg[4]/Q -type DFF DFF
add mapped point mac_acc[5]/q mac_acc_reg[5]/Q -type DFF DFF
add mapped point mac_acc[6]/q mac_acc_reg[6]/Q -type DFF DFF
add mapped point mac_acc[7]/q mac_acc_reg[7]/Q -type DFF DFF
add mapped point mac_acc[8]/q mac_acc_reg[8]/Q -type DFF DFF
add mapped point mac_acc[9]/q mac_acc_reg[9]/Q -type DFF DFF
add mapped point mac_acc[10]/q mac_acc_reg[10]/Q -type DFF DFF
add mapped point mac_acc[11]/q mac_acc_reg[11]/Q -type DFF DFF
add mapped point mac_acc[12]/q mac_acc_reg[12]/Q -type DFF DFF
add mapped point mac_acc[13]/q mac_acc_reg[13]/Q -type DFF DFF
add mapped point mac_acc[14]/q mac_acc_reg[14]/Q -type DFF DFF
add mapped point mac_acc[15]/q mac_acc_reg[15]/Q -type DFF DFF
add mapped point v_filtered[0]/q v_filtered_reg[0]/Q -type DFF DFF
add mapped point v_filtered[1]/q v_filtered_reg[1]/Q -type DFF DFF
add mapped point v_filtered[2]/q v_filtered_reg[2]/Q -type DFF DFF
add mapped point v_filtered[3]/q v_filtered_reg[3]/Q -type DFF DFF
add mapped point v_filtered[4]/q v_filtered_reg[4]/Q -type DFF DFF
add mapped point v_filtered[5]/q v_filtered_reg[5]/Q -type DFF DFF
add mapped point v_filtered[6]/q v_filtered_reg[6]/Q -type DFF DFF
add mapped point v_filtered[7]/q v_filtered_reg[7]/Q -type DFF DFF
add mapped point v_filtered[8]/q v_filtered_reg[8]/Q -type DFF DFF
add mapped point v_filtered[9]/q v_filtered_reg[9]/Q -type DFF DFF
add mapped point v_filtered[10]/q v_filtered_reg[10]/Q -type DFF DFF
add mapped point v_filtered[11]/q v_filtered_reg[11]/Q -type DFF DFF
add mapped point v_filtered[12]/q v_filtered_reg[12]/Q -type DFF DFF
add mapped point v_filtered[13]/q v_filtered_reg[13]/Q -type DFF DFF
add mapped point v_filtered[14]/q v_filtered_reg[14]/Q -type DFF DFF
add mapped point v_filtered[15]/q v_filtered_reg[15]/Q -type DFF DFF
add mapped point w_param[0]/q w_param_reg[0]111/Q -type DFF DFF
add mapped point w_param[1]/q w_param_reg[1]112/Q -type DFF DFF
add mapped point w_param[2]/q w_param_reg[2]113/Q -type DFF DFF
add mapped point w_param[3]/q w_param_reg[3]114/Q -type DFF DFF
add mapped point w_param[4]/q w_param_reg[4]115/Q -type DFF DFF
add mapped point w_param[5]/q w_param_reg[5]116/Q -type DFF DFF
add mapped point w_param[6]/q w_param_reg[6]117/Q -type DFF DFF
add mapped point w_param[7]/q w_param_reg[7]118/Q -type DFF DFF
add mapped point w_param[8]/q w_param_reg[8]119/Q -type DFF DFF
add mapped point w_param[9]/q w_param_reg[9]120/Q -type DFF DFF
add mapped point w_param[10]/q w_param_reg[10]121/Q -type DFF DFF
add mapped point w_param[11]/q w_param_reg[11]122/Q -type DFF DFF
add mapped point w_param[12]/q w_param_reg[12]123/Q -type DFF DFF
add mapped point w_param[13]/q w_param_reg[13]124/Q -type DFF DFF
add mapped point w_param[14]/q w_param_reg[14]125/Q -type DFF DFF
add mapped point w_param[15]/q w_param_reg[15]126/Q -type DFF DFF
add mapped point w_update_mult[8]/q w_update_mult_reg[8]/Q -type DFF DFF
add mapped point w_update_mult[9]/q w_update_mult_reg[9]/Q -type DFF DFF
add mapped point w_update_mult[10]/q w_update_mult_reg[10]/Q -type DFF DFF
add mapped point w_update_mult[11]/q w_update_mult_reg[11]/Q -type DFF DFF
add mapped point w_update_mult[12]/q w_update_mult_reg[12]/Q -type DFF DFF
add mapped point w_update_mult[13]/q w_update_mult_reg[13]/Q -type DFF DFF
add mapped point w_update_mult[14]/q w_update_mult_reg[14]/Q -type DFF DFF
add mapped point w_update_mult[15]/q w_update_mult_reg[15]/Q -type DFF DFF
add mapped point w_update_mult[16]/q w_update_mult_reg[16]/Q -type DFF DFF
add mapped point w_update_mult[17]/q w_update_mult_reg[17]/Q -type DFF DFF
add mapped point w_update_mult[18]/q w_update_mult_reg[18]/Q -type DFF DFF
add mapped point w_update_mult[19]/q w_update_mult_reg[19]/Q -type DFF DFF
add mapped point w_update_mult[20]/q w_update_mult_reg[20]/Q -type DFF DFF
add mapped point w_update_mult[21]/q w_update_mult_reg[21]/Q -type DFF DFF
add mapped point w_update_mult[22]/q w_update_mult_reg[22]/Q -type DFF DFF
add mapped point w_update_mult[23]/q w_update_mult_reg[23]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
